import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { gql } from '@apollo/client'
import client from '../apollo-client'

export default function Home({ streams }) {
  const router = useRouter();
  const handleClick = () => {
     console.log('Order Placed');
     router.replace('/product')
   }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app ..." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3>Home Page</h3>
        <ul>
          {streams.map((stream,id) => 
          <li key={id}><a href={`streams/${stream.slugDesc}`}>{stream.title}</a></li>
          )}
        </ul>
      <Link href='/blog'> 
           <a>Blog Page</a>
        </Link> <br/>
        
        <Link href='/users'>
          <a>Users</a>
        </Link>
        <Link href='/posts'>
          <a>Posts</a>
        </Link>
        <button onClick={handleClick}>Add Product</button>
      </main>
    </div>
  )
}

export async function getStaticProps(){
  const { data } = await client.query({
    query: gql`
        query{
          streams{
            title
            slugDesc
            streamDate
            coverImage{
              url
            }
            guestName
            description{
              raw
            }
          }
        }
    `
  });
  const { streams } = data
  return {
    props: {
       streams
    }
  }
}
